//! Validates the divergence measures against scikit-learn ground truth and
//! checks their structural properties. No rust-analyzer involved (fast tier).

use approx::assert_abs_diff_eq;
use modula_metrics::divergence::{
    Divergence, adjusted_mutual_information, adjusted_rand_index, normalized_mutual_information,
    variation_of_information,
};
use serde::Deserialize;

#[derive(Deserialize)]
struct Case {
    name: String,
    a: Vec<usize>,
    b: Vec<usize>,
    vi: f64,
    nmi: f64,
    ami: f64,
    ari: f64,
}

/// Ground truth generated by `tests/fixtures/gen_divergence.py` (scikit-learn,
/// `average_method="max"`).
const SKLEARN: &str = include_str!("fixtures/divergence_sklearn.json");

#[test]
fn matches_scikit_learn_to_1e9() {
    let cases: Vec<Case> = serde_json::from_str(SKLEARN).expect("parse fixtures");
    assert!(!cases.is_empty());
    for c in &cases {
        let d = Divergence::compute(&c.a, &c.b);
        let eps = 1e-9;
        assert_abs_diff_eq!(d.vi, c.vi, epsilon = eps);
        assert_abs_diff_eq!(d.nmi, c.nmi, epsilon = eps);
        assert_abs_diff_eq!(d.ami, c.ami, epsilon = eps);
        assert_abs_diff_eq!(d.ari, c.ari, epsilon = eps);

        // The standalone functions agree with the bundled computation.
        assert_abs_diff_eq!(variation_of_information(&c.a, &c.b), d.vi, epsilon = eps);
        assert_abs_diff_eq!(
            normalized_mutual_information(&c.a, &c.b),
            d.nmi,
            epsilon = eps
        );
        assert_abs_diff_eq!(
            adjusted_mutual_information(&c.a, &c.b),
            d.ami,
            epsilon = eps
        );
        assert_abs_diff_eq!(adjusted_rand_index(&c.a, &c.b), d.ari, epsilon = eps);

        // Report which case fails, if any.
        let _ = &c.name;
    }
}

#[test]
fn identical_partitions_are_perfect_matches() {
    let a = vec![0usize, 0, 1, 1, 2, 0, 3];
    let d = Divergence::compute(&a, &a);
    assert_abs_diff_eq!(d.vi, 0.0, epsilon = 1e-12);
    assert_abs_diff_eq!(d.nmi, 1.0, epsilon = 1e-12);
    assert_abs_diff_eq!(d.ami, 1.0, epsilon = 1e-12);
    assert_abs_diff_eq!(d.ari, 1.0, epsilon = 1e-12);
}

#[test]
fn crossing_partition_is_at_or_below_chance() {
    // A and B are statistically independent (every cell equal): the
    // chance-corrected scores sit at or below zero (here ARI is -0.5), while the
    // uncorrected NMI stays positive.
    let a = vec![0usize, 0, 1, 1];
    let b = vec![0usize, 1, 0, 1];
    let d = Divergence::compute(&a, &b);
    assert!(d.ami <= 1e-9, "ami = {}", d.ami);
    assert!(d.ari <= 1e-9, "ari = {}", d.ari);
    assert!(d.nmi >= -1e-9);
}

mod properties {
    use super::*;
    use proptest::prelude::*;

    /// A partition of `n` items into labels drawn from `0..n`.
    fn partition() -> impl Strategy<Value = Vec<usize>> {
        (1usize..18).prop_flat_map(|n| prop::collection::vec(0usize..n, n))
    }

    /// Two partitions over the same number of items.
    fn pair() -> impl Strategy<Value = (Vec<usize>, Vec<usize>)> {
        (1usize..18).prop_flat_map(|n| {
            (
                prop::collection::vec(0usize..n, n),
                prop::collection::vec(0usize..n, n),
            )
        })
    }

    /// Three partitions over the same number of items.
    fn triple() -> impl Strategy<Value = (Vec<usize>, Vec<usize>, Vec<usize>)> {
        (1usize..18).prop_flat_map(|n| {
            (
                prop::collection::vec(0usize..n, n),
                prop::collection::vec(0usize..n, n),
                prop::collection::vec(0usize..n, n),
            )
        })
    }

    proptest! {
        #[test]
        fn invariant_to_label_renaming((a, b) in pair()) {
            let base = Divergence::compute(&a, &b);
            // Apply distinct injective relabelings to each side; the grouping is
            // unchanged so every measure must be identical.
            let a2: Vec<usize> = a.iter().map(|x| x * 7 + 3).collect();
            let b2: Vec<usize> = b.iter().map(|x| 1000 - x * 2).collect();
            let relabeled = Divergence::compute(&a2, &b2);
            prop_assert!((base.vi - relabeled.vi).abs() < 1e-9);
            prop_assert!((base.nmi - relabeled.nmi).abs() < 1e-9);
            prop_assert!((base.ami - relabeled.ami).abs() < 1e-9);
            prop_assert!((base.ari - relabeled.ari).abs() < 1e-9);
        }

        #[test]
        fn measures_are_symmetric((a, b) in pair()) {
            let ab = Divergence::compute(&a, &b);
            let ba = Divergence::compute(&b, &a);
            prop_assert!((ab.vi - ba.vi).abs() < 1e-9);
            prop_assert!((ab.nmi - ba.nmi).abs() < 1e-9);
            prop_assert!((ab.ami - ba.ami).abs() < 1e-9);
            prop_assert!((ab.ari - ba.ari).abs() < 1e-9);
        }

        #[test]
        fn self_comparison_is_perfect(a in partition()) {
            let d = Divergence::compute(&a, &a);
            prop_assert!(d.vi.abs() < 1e-9);
            prop_assert!((d.nmi - 1.0).abs() < 1e-9);
            prop_assert!((d.ami - 1.0).abs() < 1e-9);
            prop_assert!((d.ari - 1.0).abs() < 1e-9);
        }

        #[test]
        fn vi_satisfies_triangle_inequality((a, b, c) in triple()) {
            let ab = variation_of_information(&a, &b);
            let bc = variation_of_information(&b, &c);
            let ac = variation_of_information(&a, &c);
            prop_assert!(ac <= ab + bc + 1e-9);
        }
    }
}
