//! Diesel table definitions, matching `migrations/.../up.sql`.

diesel::table! {
    extractions (name, version) {
        name -> Text,
        version -> Text,
        downloads -> BigInt,
        status -> Text,
        ir_path -> Nullable<Text>,
        n_items -> Nullable<Integer>,
        n_modules -> Nullable<Integer>,
        n_edges -> Nullable<Integer>,
        n_import_edges -> Nullable<Integer>,
        n_signature_edges -> Nullable<Integer>,
        n_trait_bound_edges -> Nullable<Integer>,
        n_impl_edges -> Nullable<Integer>,
        n_body_edges -> Nullable<Integer>,
        n_structs -> Nullable<Integer>,
        n_enums -> Nullable<Integer>,
        n_traits -> Nullable<Integer>,
        n_type_aliases -> Nullable<Integer>,
        n_functions -> Nullable<Integer>,
        n_pub_api_items -> Nullable<Integer>,
        elapsed_sec -> Nullable<Double>,
        prepare_sec -> Nullable<Double>,
        peak_rss_kb -> Nullable<BigInt>,
        crate_bytes -> Nullable<BigInt>,
        error -> Nullable<Text>,
        ra_version -> Nullable<Text>,
        schema_version -> Nullable<Integer>,
        categories -> Nullable<Text>,
        keywords -> Nullable<Text>,
        ts -> BigInt,
    }
}

diesel::table! {
    analyses (name, version) {
        name -> Text,
        version -> Text,
        status -> Text,
        headline -> Nullable<Double>,
        headline_depth_averaged -> Nullable<Double>,
        modularity_term -> Nullable<Double>,
        divergence_term -> Nullable<Double>,
        acyclicity_term -> Nullable<Double>,
        encapsulation_term -> Nullable<Double>,
        is_acyclic -> Nullable<Integer>,
        over_exposed_fraction -> Nullable<Double>,
        mean_leak_cost -> Nullable<Double>,
        n_real_items -> Nullable<Integer>,
        n_module_nodes -> Nullable<Integer>,
        n_sccs -> Nullable<Integer>,
        largest_scc -> Nullable<Integer>,
        modules_in_cycles -> Nullable<Integer>,
        circuits_truncated -> Nullable<Integer>,
        max_leak_cost -> Nullable<Double>,
        n_over_exposed -> Nullable<Integer>,
        n_cross_module_edges -> Nullable<Integer>,
        mean_instability -> Nullable<Double>,
        median_instability -> Nullable<Double>,
        mean_cohesion -> Nullable<Double>,
        mean_distance_main_sequence -> Nullable<Double>,
        anomaly -> Nullable<Text>,
        elapsed_ms -> Nullable<Double>,
        error -> Nullable<Text>,
        ts -> BigInt,
    }
}
